# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BanchanCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Toaster'
  # Pods for BanchanCode

  target 'BanchanCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BanchanCodeUITests' do
    # Pods for testing
  end

end
